# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba5e98b4cd15f5819278081aa4de6a15a64617f25b52dd9d9c934847077a02cb596b1a964563934d12dd09d3478b3a83c31edc30b2d556da0b0b2af3be64f136

test:
  secret_key_base: 1e2050c762f9ed586ccce1f36086e196505f323a353c4a0a9a98ceff7eaa8126b408f96cdd6bfd5d5b4e49bc109e41f37e78bd3eb14c200455e0e074f78fdaec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
